[theme]
base = "dark"
primaryColor="#EB6440"
backgroundColor="#222222"
secondaryBackgroundColor="#395b64"
textColor="#e7f6f2"


[deprecation]
showPyplotGlobalUse = false

[client]
showSidebarNavigation = false