[theme]
primaryColor="#a5c9ca"
backgroundColor="#2c3333"
secondaryBackgroundColor="#395b64"
textColor="#e7f6f2"

[theme]
primaryColor="#eb6440"
backgroundColor="#eff5f5"
secondaryBackgroundColor="#d6e4e5"
textColor="#497174"

